// Generated by CoffeeScript 1.3.2
var commands;

commands = {
  '>': function(game) {
    var pp;
    pp = game.player.getPosition();
    if (game.currentMap().getCell(pp.x, pp.y) === Map.STAIR_DOWN) {
      return game.fire('godown');
    }
  },
  '<': function(game) {
    var pp;
    pp = game.player.getPosition();
    if (game.level > 0 && game.currentMap().getCell(pp.x, pp.y) === Map.STAIR_UP) {
      return game.fire('goup');
    }
  }
};

if (typeof exports !== "undefined" && exports !== null) {
  exports.commands = commands;
} else {
  window.commands = commands;
}
