// Generated by CoffeeScript 1.3.3
var Player,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Player = (function(_super) {

  __extends(Player, _super);

  function Player(name, role, hp) {
    this.name = name;
    this.role = role;
    this.hp = hp;
    Player.__super__.constructor.call(this);
    this._position = {};
    this.experience = 0;
    this.on('godown', (function(e) {
      if (e.prevMap) {
        return e.prevMap.clearReservation(this.getPosition().x, this.getPosition().y);
      }
    }).bind(this));
    this.on('goup', (function(e) {
      if (e.prevMap) {
        return e.prevMap.clearReservation(this.getPosition().x, this.getPosition().y);
      }
    }).bind(this));
  }

  Player.prototype.born = function(map) {
    var nextPos;
    nextPos = {
      x: Math.floor(Math.random() * map.width),
      y: Math.floor(Math.random() * map.height)
    };
    if (map.isWalkable(nextPos.x, nextPos.y)) {
      this._position = nextPos;
      return map.reserveCell(this._position.x, this._position.y, this);
    } else {
      return this.born(map);
    }
  };

  Player.prototype.getMaxHP = function() {
    var maxHP;
    maxHP = [12, 18, 26, 36, 48, 62, 80, 100];
    return maxHP[Math.floor(this.experience)] || maxHP[maxHP.length - 1];
  };

  Player.prototype.getPower = function() {
    var i, power;
    power = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 4; _i <= 20; i = _i += 2) {
        _results.push(i);
      }
      return _results;
    })();
    return power[Math.floor(this.experience)] || power[power.length - 1];
  };

  Player.prototype.walk = function(map, direction) {
    var DOWN, LEFT, RIGHT, UP, m, nextPos;
    UP = 'u';
    DOWN = 'd';
    RIGHT = 'r';
    LEFT = 'l';
    nextPos = {
      x: this._position.x,
      y: this._position.y
    };
    switch (direction) {
      case UP:
        nextPos.y -= 1;
        break;
      case DOWN:
        nextPos.y += 1;
        break;
      case RIGHT:
        nextPos.x += 1;
        break;
      case LEFT:
        nextPos.x -= 1;
    }
    if (map.isWalkable(nextPos.x, nextPos.y)) {
      map.clearReservation(this._position.x, this._position.y);
      this._position = nextPos;
      map.reserveCell(this._position.x, this._position.y, this);
    } else if (m = map.getReservation(nextPos.x, nextPos.y)) {
      this.attack(m);
    }
    return this.fire('move', {
      position: this._position
    });
  };

  Player.prototype.attack = function(enemy) {
    enemy.hp -= this.getPower();
    if (enemy.isDead()) {
      this.experience += enemy.gainExp || 0.01;
      enemy.fire('die');
    }
    return this.fire('attack', {
      me: this,
      enemy: enemy
    });
  };

  Player.prototype.isDead = function() {
    if (this.hp < 1) {
      return true;
    } else {
      return false;
    }
  };

  Player.prototype.getPosition = function() {
    return this._position;
  };

  Player.prototype.setPosition = function(x, y) {
    return this._position = {
      x: x,
      y: y
    };
  };

  return Player;

})(EventEmitter);
