// Generated by CoffeeScript 1.3.3
var Tile;

Tile = (function() {
  var CELL_SIZE, HEIGHT, WIDTH, loadImage;

  CELL_SIZE = 16;

  WIDTH = CELL_SIZE * 25;

  HEIGHT = CELL_SIZE * 18;

  loadImage = function(n) {
    var img;
    img = new Image();
    img.src = './nhtiles/' + n + '.png';
    return img;
  };

  Tile.images = (function() {
    return {
      map: {
        blank: loadImage(861),
        room: loadImage(849),
        path: loadImage(850),
        wall_vert: loadImage(830),
        wall_horiz: loadImage(831),
        trap: loadImage(849),
        trap_active: loadImage(874),
        stair_up: loadImage(851),
        stair_down: loadImage(852),
        item: loadImage(903)
      },
      monster: {
        player: loadImage(388),
        lichen: loadImage(159),
        'grid bug': loadImage(117),
        newt: loadImage(326),
        jackal: loadImage(12),
        gnome: loadImage(166),
        dwarf: loadImage(45),
        rothe: loadImage(82),
        dragon: loadImage(147)
      }
    };
  })();

  function Tile(cvid) {
    this.surface = document.getElementById(cvid).getContext('2d');
  }

  Tile.prototype.update = function(x, y, type, name) {
    try {
      return this.surface.drawImage(Tile.images[type][name], x * CELL_SIZE, y * CELL_SIZE);
    } catch (e) {
      return alert(type + ' ' + name);
    }
  };

  return Tile;

})();
