// Generated by CoffeeScript 1.3.3
var message, traplist;

message = typeof require !== "undefined" && require !== null ? require('messagelist').messagelist : messagelist;

traplist = [
  function(game) {
    game.fire('message', {
      message: message.trap.hole
    });
    return game.fire('godown');
  }, function(game) {
    game.fire('message', {
      message: message.trap.stone
    });
    return game.player.hp -= 4;
  }, function(game) {
    var f, map, pp;
    game.fire('message', {
      message: message.trap.teleport
    });
    pp = game.player.getPosition();
    map = game.currentMap();
    return (f = function() {
      var x, y;
      x = Math.floor(Math.random() * map.width);
      y = Math.floor(Math.random() * map.height);
      if (map.isWalkable(x, y)) {
        map.clearReservation(pp.x, pp.y);
        map.reserveCell(x, y);
        return game.player.setPosition(x, y);
      } else {
        return f();
      }
    })();
  }
];
