// Generated by CoffeeScript 1.3.3
var ninjitsulist_ja;

ninjitsulist_ja = [
  {
    name: '回復の術',
    jitsu: (function(game) {
      return game.player.hp = game.player.getMaxHP();
    }),
    description: 'HPを最大値まで回復する.',
    message: 'あなたは回復の術を使った。ピロリロリン♪ あなたのHPは回復した.'
  }, {
    name: '超攻撃の術',
    jitsu: (function(game) {
      var cells, m, pp, _i, _len, _results;
      pp = game.player.getPosition();
      cells = game.currentMap().getNearByCells(pp.x, pp.y);
      _results = [];
      for (_i = 0, _len = cells.length; _i < _len; _i++) {
        m = cells[_i];
        if ((m != null) && m) {
          _results.push(m.hp = 0);
        }
      }
      return _results;
    }),
    description: '近接するマスにいる敵を全て倒す(経験値は入らない)',
    message: 'ボシュッ！あなたは軽い爆発を起こした。近接する敵はいなくなった.'
  }, {
    name: '隠れ身の術',
    jitsu: (function(game) {
      var ctr, f, i, map, pp, _i;
      pp = game.player.getPosition();
      map = game.currentMap();
      map.clearReservation(pp.x, pp.y);
      ctr = 0;
      game.on('turn', function() {
        return ctr++;
      });
      for (i = _i = 0; _i < 20; i = ++_i) {
        game.fire('turn');
      }
      return (f = function() {
        if (ctr >= 20) {
          return game.player.born(map);
        } else {
          return setTimeout(f, 10);
        }
      })();
    }),
    description: '20ターンの間、残像を残して身を隠し、ランダムな位置にテレポートする',
    message: 'あなたは20ターン身を隠した。馬鹿めそっちは残像だ！.'
  }, {
    name: '階層跳躍の術',
    jitsu: (function(game) {
      var i, tolevel, _i, _ref, _results;
      tolevel = Math.floor(Math.random() * game.level);
      if (tolevel !== game.level) {
        _results = [];
        for (i = _i = _ref = game.level; _ref <= tolevel ? _i < tolevel : _i > tolevel; i = _ref <= tolevel ? ++_i : --_i) {
          _results.push(game.fire('goup'));
        }
        return _results;
      }
    }),
    description: '予測不能な階まで戻る',
    message: '頭がくらくらする。あなたは階層跳躍を終えた..'
  }
];
